[2017-11-18 09:07:56] -> ERROR -> [Errno 2] No such file or directory: 'schema.json'
[2017-11-18 09:16:18] -> ERROR -> 'primaryKe'
[2017-11-18 09:16:52] -> ERROR -> 'primaryKe'
[2017-11-18 09:28:19] -> ERROR -> __init__() takes exactly 4 arguments (2 given)
[2017-11-18 09:30:28] -> ERROR -> __init__() takes exactly 4 arguments (2 given)
[2017-11-18 09:47:33] -> ERROR -> 'dict' object has no attribute 'append'
[2017-11-18 10:11:26] -> ERROR -> coercing to Unicode: need string or buffer, int found
[2017-11-18 10:25:15] -> ERROR -> 'users' is not in list
[2017-11-18 10:26:20] -> ERROR -> 'list' object has no attribute 'where'
[2017-11-18 10:28:45] -> ERROR -> list indices must be integers, not tuple
[2017-11-18 10:34:39] -> ERROR -> too many values to unpack
[2017-11-18 10:34:51] -> ERROR -> too many values to unpack
[2017-11-18 10:44:47] -> ERROR -> 'users' is not in list
[2017-11-18 10:45:01] -> ERROR -> 'users' is not in list
[2017-11-18 10:45:20] -> ERROR -> substring not found
[2017-11-18 10:45:30] -> ERROR -> expected a string or other character buffer object
[2017-11-18 10:51:57] -> ERROR -> global name 'get_item_in_pks' is not defined
[2017-11-18 10:52:23] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:54:23] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:54:36] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:06] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:15] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:20] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:57:50] -> ERROR -> an integer is required
[2017-11-18 10:58:54] -> ERROR -> u'phones' is not in list
[2017-11-18 10:59:05] -> ERROR -> u'id' is not in list
[2017-11-18 10:59:14] -> ERROR -> -2093098020 is not in list
[2017-11-18 11:04:00] -> ERROR -> list.remove(x): x not in list
[2017-11-18 11:05:04] -> ERROR -> list.remove(x): x not in list
[2017-11-18 11:11:47] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:13:56] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:15:57] -> ERROR -> get_item_in_pks() takes exactly 3 arguments (2 given)
[2017-11-18 11:27:44] -> ERROR -> [Errno 2] No such file or directory: 'schema.json'
[2017-11-18 11:31:59] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:51:17] -> ERROR -> append() takes exactly one argument (3 given)
[2017-11-18 12:02:23] -> ERROR -> not all arguments converted during string formatting
[2017-11-18 12:02:32] -> ERROR -> not all arguments converted during string formatting
[2017-11-18 12:03:15] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:25] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:28] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:38] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:43] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:05:21] -> ERROR -> 'generator' object has no attribute 'item'
[2017-11-18 12:55:02] -> ERROR -> global name 'pks' is not defined
[2017-11-18 12:55:53] -> ERROR -> global name 'pks' is not defined
[2017-11-18 12:58:05] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 12:58:42] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 12:58:57] -> ERROR -> local variable 'pks' referenced before assignment
